services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: macuin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api_fastapi
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/macuin
    volumes:
      - ./api_fastapi:/app
      - ./cliente_flask/static:/app/static        
      - ./cliente_flask/templates:/app/templates 

  cliente:
    build: ./cliente_flask
    ports:
      - "5001:5000"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000
    volumes:
      - ./cliente_flask:/app

  admin:
    build: ./admin_laravel
    ports:
      - "8002:80"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000
    volumes:
      - ./admin_laravel:/var/www/html
      - /var/www/html/vendor

volumes:
  postgres_data: