services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: macuin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./static:/app/static        # 🔥 CLAVE (arregla tu error)
      - ./templates:/app/templates  # 🔥 CLAVE

  cliente:
    build: ./cliente_flask
    ports:
      - "5001:5000"
    volumes:
      - ./cliente_flask:/app

  admin:
    build: ./admin_laravel
    ports:
      - "8001:80"

volumes:
  postgres_data: