//tealium universal tag - utag.115 ut4.0.202603200255, Copyright 2026 Tealium.com Inc. All Rights Reserved.
var _gre=_gre||[];try{(function(id,loader){var u={id:id};utag.o[loader].sender[id]=u;u.ev={view:1,link:1};u.initialized=false;u.scriptrequested=false;u.toBoolean=function(val){val=val||'';return val===true||val.toLowerCase()==='true'||val.toLowerCase()==='on';};u.clearEmptyKeys=function(object){Object.keys(object).forEach(function(key){if(object[key]===''||object[key]===undefined){delete object[key];}});return object;};u.deepMergeObject=function(targetObject,sourceObject){targetObject=targetObject||{};sourceObject=sourceObject||{};var copyTargetObject=JSON.parse(JSON.stringify(targetObject));var copySourceObject=JSON.parse(JSON.stringify(sourceObject));Object.keys(copySourceObject).forEach(function(key){if(typeof copySourceObject[key]==="object"&&!Array.isArray(copySourceObject[key])){copyTargetObject[key]=u.deepMergeObject(copyTargetObject[key],copySourceObject[key]);}else{copyTargetObject[key]=copySourceObject[key];}});return copyTargetObject;}
u.clearEmptyKeysDeep=function(object){Object.keys(object).forEach(function(key){if(typeof object[key]==='object'){u.clearEmptyKeysDeep(object[key]);if(utag.ut.isEmptyObject(object[key])){try{delete object[key];}catch(e){object[key]=undefined;}}}
else if(object[key]===''||object[key]===undefined){delete object[key];}});return object;};u.mapFunc=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.mapFunc(arr,obj[i],item);}else{obj[i]=item;}};u.getProp=function(object,keys,defaultVal){keys=Array.isArray(keys)?keys:keys.split('.');object=object[keys[0]];if(object&&keys.length>1){return u.getProp(object,keys.slice(1),defaultVal);}
return object===undefined?defaultVal:object;}
u.setProp=function(obj,path,value){const pathArray=Array.isArray(path)?path:path.match(/([^[.\]])+/g)
var acc=obj;pathArray.forEach((key,index)=>{if(acc[key]===undefined)acc[key]={}
if(index===pathArray.length-1)acc[key]=value
acc=acc[key]})}
u.generateProductList=function(data){var product=data.productDetails.product;var quantity=data.productDetails.quantity;var products=product.id.map(function(productId,index){return u.clearEmptyKeysDeep({product:{id:productId,priceInfo:{price:product.priceInfo.price[index]}},quantity:quantity[index]});});return products}
u.loaderCallback=function(){utag.DB('send:115:CALLBACK');u.initialized=true;u.callback();utag.DB('send:115:CALLBACK:COMPLETE');};u.callback=function(){u.data.events.forEach(function(eventName){u.sendEvent(eventName);});};u.hasEventRequiredParams=function(eventName,data){var requiredFields=u.EVENTS_LIST[eventName].requiredFields;if(!requiredFields.length){return true;}
const res=requiredFields.every(function(fieldPath){var value=u.getProp(data,fieldPath);var isEmpty=typeof value==='object'?utag.ut.isEmptyObject(value):utag.ut.isEmpty(value);if(isEmpty){utag.DB('Event '+eventName+' not fired: Required attribute '+fieldPath+' not populated');return false;}
return true;})
return res;}
u.EVENTS_LIST={'add-to-cart':{name:'add-to-cart',requiredFields:['productDetails.product.id','productDetails.quantity']},'category-page-view':{name:'category-page-view',requiredFields:['pageCategories']},'detail-page-view':{name:'detail-page-view',requiredFields:['productDetails.product.id']},'home-page-view':{name:'home-page-view',requiredFields:[]},'purchase-complete':{name:'purchase-complete',requiredFields:['productDetails.product.id','productDetails.quantity','purchaseTransaction.revenue','purchaseTransaction.currencyCode']},search:{name:'search',requiredFields:['productDetails.product.id']},'shopping-cart-page-view':{name:'shopping-cart-page-view',requiredFields:['productDetails.product.id']},};u.sendEvent=function(eventName){var data=u.deepMergeObject(u.data,u.data[eventName]);if(!u.hasEventRequiredParams(eventName,data)){return;}
var eventData={userInfo:{userId:data.userInfo.userId},eventType:eventName,visitorId:data.visitorId,attributes:data.attributes,attributionToken:data.attributionToken,};utag.ut.merge(eventData,data.custom)
var eventRequiredData={}
switch(eventName){case u.EVENTS_LIST['add-to-cart'].name:{eventRequiredData={productDetails:u.generateProductList(data)}
break;}
case u.EVENTS_LIST['category-page-view'].name:{eventRequiredData={pageCategories:data.pageCategories,};break;}
case u.EVENTS_LIST['detail-page-view'].name:{eventRequiredData={productDetails:u.generateProductList(data)};break;}
case u.EVENTS_LIST['home-page-view'].name:{eventRequiredData={};break;}
case u.EVENTS_LIST['purchase-complete'].name:{eventRequiredData={productDetails:u.generateProductList(data),purchaseTransaction:{id:data.purchaseTransaction.id,revenue:data.purchaseTransaction.revenue,currencyCode:data.purchaseTransaction.currencyCode}};break;}
case u.EVENTS_LIST.search.name:{eventRequiredData={searchQuery:data.searchQuery,pageCategories:data.pageCategories,productDetails:u.generateProductList(data),completionDetail:{completionAttributionToken:data.completionDetail.completionAttributionToken,selectedSuggestion:data.completionDetail.selectedSuggestion,selectedPosition:data.completionDetail.selectedPosition}};break;}
case u.EVENTS_LIST['shopping-cart-page-view'].name:{eventRequiredData={productDetails:u.generateProductList(data)};break;}}
eventData=u.deepMergeObject(eventData,eventRequiredData);u.clearEmptyKeysDeep(eventData);_gre.push(['logEvent',eventData]);window.cloud_retail.logEvent(_gre)};u.map={"tealium_visitor_id":"visitorId","eventType:addToCart":"add-to-cart","eventType:In-Stock Near You: Set Store and Add to Cart":"add-to-cart","productIdList":"add-to-cart.productDetails.product.id,search.productDetails.product.id,purchase-complete.productDetails.product.id","productQuantityList":"purchase-complete.productDetails.quantity","currencyCode":"purchase-complete.purchaseTransaction.currencyCode","combinedOrderId":"purchase-complete.purchaseTransaction.id","retailProductQuantity":"add-to-cart.productDetails.quantity,detail-page-view.productDetails.quantity","productPrice":"detail-page-view.productDetails.product.priceInfo.price","retailEvent:product-detail":"detail-page-view","retailEvent:purchase":"purchase-complete","retailEvent:search":"search","retailProductId":"detail-page-view.productDetails.product.id","retailProductPrice":"detail-page-view.productDetails.product.priceInfo.price","_sm_115_12":"debug","retailOffset":"custom.offset","retailPageCategory":"pageCategories,search.pageCategories","retailOrderBy":"custom.orderBy","grandTotalAmount":"purchaseTransaction.revenue","retailApiKey":"apiKey","retailProjectNumber":"projectNumber","retailGCMID":"userInfo.userId","retailSearchQuery":"searchQuery,search.searchQuery","attributionToken":"attributionToken","filter":"custom.filter","retailSearchPlatform":"custom.experimentIds"};u.extend=[function(a,b){try{b['_sm_115_12']="true";}catch(e){utag.DB(e);}},function(a,b,c,d,e,f,g){if(1){d=b['ut.env'];if(typeof d=='undefined')return;c=[{'dev':'508485490819'},{'qa':'429622201647'},{'prod':'571913228573'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['retailProjectNumber']=c[e][f];m=true};};if(m)break};}},function(a,b,c,d,e,f,g){if(1){d=b['ut.env'];if(typeof d=='undefined')return;c=[{'dev':'AIzaSyDL4xBzwtPQvmNHRNmsShzRCwCkTaMLiHk'},{'qa':'AIzaSyDFyr5cnNAzCzr0UDDIyskxSYlzj308zMk'},{'prod':'AIzaSyAleBmpzlEmqWxv7Jb0fPbjGll4Y9N0x3k'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['retailApiKey']=c[e][f];m=true};};if(m)break};}},function(a,b){try{if(1){if(a=='view'){if((b.pageType&&b.pageType=='search_results_shelf')||(b.pageType&&b.pageType=='catalog_shelf')||(b.pageType&&b.pageType=='Brand Profile')){b.retailEvent="search";}else if(b.pageType&&b.pageType=='catalog_product-detail'&&b.productId&&b.productId!==''&&b.productPrice&&b.productPrice!==''){b.retailEvent="product-detail";b.retailProductQuantity=["1"];b.retailProductId=b.productId;b.retailProductPrice=b.productPrice;}else if(b.pageType&&b.pageType=='cart'){b.retailEvent="cart";}else if(b.pageType&&b.pageType=='order-confirmation'){b.retailEvent="purchase";}}
if(b.eventType&&(b.eventType==="addToCart"||b.eventType==="In-Stock Near You: Set Store and Add to Cart")&&b.productIdList&&b.productIdList!==''&&b.productQuantityList&&b.productQuantityList!==''){b.retailProductQuantity=b.productQuantityList;}
if(b.searchKeyword&&b.searchKeyword!==''&&b["qp.redirectUrl"]!=="true"){b.retailSearchQuery=b.searchKeyword;}
if(a=='view'){if(typeof b.pageDepth==="string"&&b.pageDepth.trim()!==""){b.retailOffset=parseInt(b.pageDepth.split(" ")[0],10)-1;}else if(typeof utag_data.pageDepth==="string"&&utag_data.pageDepth.trim()!==""){b.retailOffset=parseInt(utag_data.pageDepth.split(" ")[0],10)-1;}}
if(a=='view'){if((!window.location.pathname.includes('/searchresult')||window.location.pathname.includes('redirectUrl=true'))&&((b.pageType&&b.pageType=='search_results_shelf')||(b.pageType&&b.pageType=='catalog_shelf')||(b.pageType&&b.pageType=='Brand Profile'))){let category=window.location.pathname.split('/');if(category.length>2){b.retailPageCategory=[category[1]+' > '+category[2]];}else{b.retailPageCategory=[category[1]]||'';}}}
if(typeof b.searchPlatform==="string"&&b.searchPlatform.trim()!==""){b.retailSearchPlatform=[b.searchPlatform];}else if(typeof utag_data.searchPlatform==="string"&&utag_data.searchPlatform.trim()!==""){b.retailSearchPlatform=[utag_data.searchPlatform];}
if((b.authenticationStatus===true||utag_data.authenticationStatus===true)&&(b.GCMID||utag_data.GCMID)){b.retailGCMID=b.GCMID||utag_data.GCMID;}
if(a=='view'&&b['qp.sort']){const sortMap={'price-asc':'price','price-desc':'price desc','recently-added':'attributes.new_item_b desc','customer-rating':'rating desc','best-sellers':'attributes.units_sold_i desc','recently-added-desc':'attributes.new_item_b desc','customer-rating-desc':'rating desc','best-seller-desc':'attributes.units_sold_i desc','best-seller-asc':'attributes.units_sold_i asc'};b.retailOrderBy=sortMap[b['qp.sort']]||'';}
if(a=='view'&&b.searchedTerms&&b.searchedTerms!==''){let variable=[];for(let i=0;i<b.searchedTerms.length;i++){variable.push(b.searchedTerms[i].replace(/"/g,""));}
b.retailSearchedTerms=variable.toString();}
if(b.grandTotalAmount&&b.grandTotalAmount!==''){b.retailTotalAmount=b.grandTotalAmount;}}}catch(e){utag.DB(e)}}];u.send=function(utag_event,data_layer){if(!u.ev[utag_event]&&u.ev.all===undefined){utag.DB('send:115:EVENT NOT SUPPORTED:COMPLETE');return;}
utag.DB('send:115');utag.DB(data_layer);var a,b,c,d,e,f,g,h,query_params;a=utag_event;b=data_layer;u.data={qsp_delim:'&',kvp_delim:'=',base_url:'https://www.gstatic.com/retail/v2_event.js',projectNumber:'',apiKey:'',debug:false,locationId:'global',catalogId:'default_catalog',cartId:'',pageCategories:'',searchQuery:'',completionDetail:{completionAttributionToken:'',selectedSuggestion:'',selectedPosition:'',},attributionToken:'',visitorId:data_layer['tealium_visitor_id'],userInfo:{userId:''},attributes:{},purchaseTransaction:{id:'',revenue:'',currencyCode:''},productDetails:{product:{id:[],priceInfo:{price:[]}},quantity:[],},custom:{},events:[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB('send:115:EXTENSIONS');utag.DB(data_layer);query_params=[];Object.keys(utag.loader.GV(u.map)).forEach(function(mapping_key){if(data_layer[mapping_key]!==undefined&&data_layer[mapping_key]!==''){var destinations=u.map[mapping_key].split(',');destinations.forEach(function(parameter){u.mapFunc(parameter.split('.'),u.data,data_layer[mapping_key]);});}else{var event_destinations=mapping_key.split(':');if(event_destinations.length===2&&String(data_layer[event_destinations[0]])===String(event_destinations[1])){if(u.map[mapping_key]){u.data.events=u.data.events.concat(u.map[mapping_key].split(','));}}}});utag.DB('send:115:MAPPINGS');utag.DB(u.data);var eCommerceMapping=[{eCommerceData:data_layer._corder,name:'purchaseTransaction.id',isArray:false},{eCommerceData:data_layer._csubtotal,name:'purchaseTransaction.revenue',isArray:false},{eCommerceData:data_layer._ccurrency,name:'purchaseTransaction.currencyCode',isArray:false},{eCommerceData:data_layer._cprod,name:'productDetails.product.id',isArray:true},{eCommerceData:data_layer._cprice,name:'productDetails.product.priceInfo.price',isArray:true},{eCommerceData:data_layer._cquan,name:'productDetails.quantity',isArray:true}];eCommerceMapping.forEach(function(dataObject){if(!dataObject.isArray){var propValue=u.getProp(u.data,dataObject.name)||dataObject.eCommerceData||'';u.setProp(u.data,dataObject.name,propValue);}else if(u.getProp(u.data,dataObject.name,[]).length===0&&dataObject.eCommerceData!==undefined&&dataObject.isArray){u.setProp(u.data,dataObject.name,dataObject.eCommerceData.slice(0));}});if(!u.data.projectNumber||!u.data.apiKey){utag.DB(u.id+': Tag not fired: Required attribute "projectNumber" or "apiKey"  not populated');return;}
if(u.initialized){u.callback();}else{if(!u.scriptrequested){u.scriptrequested=true;_gre.push(['apiKey',u.data.apiKey]);_gre.push(['projectId',u.data.projectNumber]);_gre.push(['locationId',u.data.locationId]);_gre.push(['catalogId',u.data.catalogId]);_gre.push(['debug',u.toBoolean(u.data.debug)]);utag.ut.loader({type:'script',src:u.data.base_url,cb:u.loaderCallback,loc:'script',id:'utag_115',attrs:{}});}}
utag.DB('send:115:COMPLETE');};utag.o[loader].loader.LOAD(id);}('115','autozone.b2c-responsive-mexico'));}catch(error){utag.DB(error);}
